name: Run Python App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-app:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9.6'  # Thay '3.x' bằng phiên bản Python bạn cần

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip        

    - name: Run app
      run: python app.py
